version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: thot-mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: <admin-user>
            MONGO_INITDB_ROOT_PASSWORD: <admin-password>
            MONGO_INITDB_DATABASE: <database to create>
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    backend:
        image: thot-backend:latest
        container_name: thot-backend
        environment:
            JAVA_TOOL_OPTIONS: -Dexternal.configuration.path=/properties
        volumes:
            - ./properties:/properties:ro
        ports:
            - 8080:8080
